/**
 * Bundle the demo project into the web build.
 *
 * The browser has no filesystem, so the demo project is compiled into a
 * module of path/content pairs. It is then handed to the *same* `analyze`
 * the CLI runs against the same files on disk -- which is the only reason
 * the demo is worth anything as a demonstration. It is not a fixture of
 * results; it is a real analysis of a fake project.
 *
 * Run with `--check` to verify the generated module is current. CI runs that,
 * so the demo cannot drift from the fixtures the CLI is tested against.
 */

import { readFile, readdir, writeFile } from 'node:fs/promises'
import { join, relative, resolve, sep } from 'node:path'

import { SKIPPED_DIRECTORIES } from '../src/engine/limits.ts'

const ROOT = resolve(import.meta.dirname, '..')
const SOURCE = join(ROOT, 'fixtures', 'demo-project')
const TARGET = join(ROOT, 'src', 'demo-tree.generated.ts')

/** Extensions stored as base64 because they are not text. */
const BINARY = new Set([
  '.pkl',
  '.pt',
  '.pth',
  '.bin',
  '.ckpt',
  '.npy',
  '.npz',
  '.safetensors',
  '.onnx',
  '.gguf',
  '.h5',
  '.keras',
  '.joblib',
  '.model',
  '.tflite',
])

async function walk(directory: string): Promise<string[]> {
  const out: string[] = []
  for (const item of await readdir(directory, { withFileTypes: true })) {
    if (item.isDirectory()) {
      if (SKIPPED_DIRECTORIES.has(item.name)) continue
      out.push(...(await walk(join(directory, item.name))))
      continue
    }
    if (item.isFile()) out.push(join(directory, item.name))
  }
  return out
}

function isBinary(path: string): boolean {
  const at = path.lastIndexOf('.')
  return at === -1 ? false : BINARY.has(path.slice(at).toLowerCase())
}

const files = (await walk(SOURCE)).sort()
const entries: string[] = []
let textBytes = 0
let binaryBytes = 0

for (const absolute of files) {
  const path = relative(SOURCE, absolute).split(sep).join('/')
  const data = await readFile(absolute)
  if (isBinary(path)) {
    binaryBytes += data.length
    entries.push(`  { path: ${JSON.stringify(path)}, base64: ${JSON.stringify(data.toString('base64'))} },`)
  } else {
    textBytes += data.length
    entries.push(`  { path: ${JSON.stringify(path)}, text: ${JSON.stringify(data.toString('utf8'))} },`)
  }
}

const body = `/**
 * GENERATED by scripts/demo-tree.ts. Do not edit.
 *
 * The demo project from fixtures/demo-project, compiled for the browser. CI
 * checks that this file matches those fixtures, so the project the web app
 * analyses and the project the CLI is tested against cannot drift apart.
 *
 * ${files.length} files, ${textBytes} bytes of text and ${binaryBytes} bytes of binary fixtures.
 */

export interface DemoFile {
  readonly path: string
  readonly text?: string
  readonly base64?: string
}

export const DEMO_PROJECT_NAME = 'atlas-triage'

export const DEMO_FILES: readonly DemoFile[] = [
${entries.join('\n')}
]
`

if (process.argv.includes('--check')) {
  let current = ''
  try {
    current = await readFile(TARGET, 'utf8')
  } catch {
    console.error('::error::src/demo-tree.generated.ts is missing. Run `npm run demo-tree`.')
    process.exit(1)
  }
  if (current !== body) {
    console.error(
      '::error::src/demo-tree.generated.ts is out of date with fixtures/demo-project. Run `npm run demo-tree`.',
    )
    process.exit(1)
  }
  console.log(`Demo tree matches the fixtures (${files.length} files).`)
} else {
  await writeFile(TARGET, body, 'utf8')
  console.log(`Wrote src/demo-tree.generated.ts (${files.length} files).`)
}

// A cheap guard against the demo quietly becoming a megabyte of bundle.
const total = textBytes + binaryBytes
if (total > 512 * 1024) {
  console.error(`::error::The demo project is ${(total / 1024).toFixed(0)} KiB; keep it under 512.`)
  process.exit(1)
}
