/**
 * Generate the 403, 404 and 500 pages.
 *
 * They are served by the host without the bundle, so each one has to render
 * with no stylesheet, no script and no network. Generating all three from one
 * template is how three near-identical documents stay identical; `--check`
 * proves they still match, which CI runs.
 *
 * Each page carries the stripe, because the mark is the product's glyph and
 * a reader who lands on a 404 should still know whose 404 it is.
 */

import { readFile, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'

const ROOT = resolve(import.meta.dirname, '..')
const PUBLIC = join(ROOT, 'public')

interface Page {
  readonly status: number
  readonly title: string
  readonly what: string
  readonly why: string
  readonly fix: string
}

const PAGES: readonly Page[] = [
  {
    status: 403,
    title: 'Not permitted',
    what: 'The host refused this request.',
    why: 'DEADWEIGHT itself has no accounts and no server-side state, so this is the hosting in front of it, not the tool.',
    fix: 'Open the tool at its root, or run the command line, which needs no host at all.',
  },
  {
    status: 404,
    title: 'Nothing here',
    what: 'There is no page at this address.',
    why: 'DEADWEIGHT is a single page: the views are states of it rather than separate URLs, so a deep link to one of them does not resolve.',
    fix: 'Go to the root and pick a view from the navigation.',
  },
  {
    status: 500,
    title: 'The host failed',
    what: 'The server could not deliver the page.',
    why: 'Nothing was analysed and nothing was lost: DEADWEIGHT runs in your browser and keeps no state on a server.',
    fix: 'Reload. If it persists, run the command line, which does the same analysis with no host involved.',
  },
]

function render(page: Page): string {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${page.status} &middot; ${page.title} &middot; DEADWEIGHT</title>
    <meta name="robots" content="noindex" />
    <!--
      GENERATED by scripts/error-pages.ts. Do not edit.

      Self-contained on purpose: no stylesheet, no script, no font request.
      This page exists to report a failure, and a page that needs the network
      to render a network failure is not much use.
    -->
    <style>
      :root {
        color-scheme: dark light;
        --bg: #0a0c10;
        --panel: #10131a;
        --line: #1f2531;
        --ink: #f0f4f9;
        --muted: #a9b4c4;
        --faint: #6e7b8d;
        --accent: #56b6f0;
        --code: #e85e5c;
      }
      @media (prefers-color-scheme: light) {
        :root {
          --bg: #f3f6fa;
          --panel: #ffffff;
          --line: #e1e6ed;
          --ink: #0d1117;
          --muted: #445060;
          --faint: #697688;
          --accent: #0b6cb0;
          --code: #bd2c34;
        }
      }
      * {
        box-sizing: border-box;
      }
      body {
        margin: 0;
        min-height: 100vh;
        display: grid;
        place-items: center;
        padding: 32px;
        background: var(--bg);
        color: var(--ink);
        font: 15px/1.6 system-ui, -apple-system, 'Segoe UI', sans-serif;
      }
      main {
        width: 100%;
        max-width: 560px;
      }
      .mark {
        display: flex;
        align-items: flex-end;
        gap: 3px;
        margin-bottom: 28px;
      }
      .mark i {
        display: block;
        width: 4px;
        height: 12px;
        border-radius: 1px;
        background: var(--faint);
      }
      .mark i:nth-child(3) {
        height: 18px;
        background: var(--code);
      }
      .mark span {
        margin-left: 10px;
        font-size: 13px;
        font-weight: 600;
        letter-spacing: 0.02em;
        align-self: center;
      }
      .status {
        font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
        font-size: 11px;
        letter-spacing: 0.16em;
        text-transform: uppercase;
        color: var(--faint);
      }
      h1 {
        margin: 10px 0 0;
        font-size: 30px;
        line-height: 1.1;
        letter-spacing: -0.02em;
        font-weight: 500;
      }
      dl {
        margin: 28px 0 0;
        border-top: 1px solid var(--line);
      }
      dt {
        font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
        font-size: 11px;
        letter-spacing: 0.12em;
        text-transform: uppercase;
        color: var(--faint);
        margin-top: 20px;
      }
      dd {
        margin: 6px 0 0;
        color: var(--muted);
      }
      a {
        color: var(--accent);
        text-decoration: none;
        border-bottom: 1px solid currentColor;
      }
      footer {
        margin-top: 32px;
        padding-top: 16px;
        border-top: 1px solid var(--line);
        font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
        font-size: 11px;
        color: var(--faint);
      }
    </style>
  </head>
  <body>
    <main>
      <p class="mark" aria-label="DEADWEIGHT">
        <i></i><i></i><i></i><i></i><i></i><i></i><span>DEADWEIGHT</span>
      </p>
      <p class="status">Error ${page.status}</p>
      <h1>${page.title}</h1>
      <dl>
        <dt>What happened</dt>
        <dd>${page.what}</dd>
        <dt>Why it matters</dt>
        <dd>${page.why}</dd>
        <dt>What to do</dt>
        <dd>${page.fix} <a href="/">Open DEADWEIGHT</a></dd>
      </dl>
      <footer>AI model &amp; skill supply-chain analyzer &middot; runs entirely in your browser</footer>
    </main>
  </body>
</html>
`
}

const check = process.argv.includes('--check')
let failures = 0

for (const page of PAGES) {
  const target = join(PUBLIC, `${page.status}.html`)
  const body = render(page)
  if (check) {
    let current: string
    try {
      current = await readFile(target, 'utf8')
    } catch {
      console.error(`::error::public/${page.status}.html is missing. Run \`npm run error-pages\`.`)
      failures += 1
      continue
    }
    if (current !== body) {
      console.error(
        `::error::public/${page.status}.html does not match the template. Run \`npm run error-pages\`.`,
      )
      failures += 1
    }
    continue
  }
  await writeFile(target, body, 'utf8')
}

if (check) {
  if (failures > 0) process.exit(1)
  console.log(`All ${PAGES.length} error pages match the template.`)
} else {
  console.log(`Wrote ${PAGES.length} error pages into public/.`)
}
